github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local use

title: [Eclipse GlassFish]
description: [Open Source Jakarta EE Platform Implementation]

# sidebar links url
links:
  download: download
  source: https://github.com/eclipse-ee4j/glassfish
  mailinglist: https://accounts.eclipse.org/mailing-list/glassfish-dev
  #javadocs:
  docs: documentation
  #faq:
  hide_issuetracker: false #set explicitly to 'true' if you don't want to have the issue tracker link displayed

include:
  - LICENSE.md
  - CONTRIBUTING.md
